name: Build

on:
  push:
    branches: [ "main" ]
  pull_request:

env:
  CARGO_TERM_COLOR: always

jobs:
  ci-linux:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Add Rust target
      run: rustup target add riscv32imac-unknown-none-elf
    - name: Build debug
      run: cargo build
    - name: Build release
      run: cargo build --release
