name: Code formatting check

on:
  push:
    branches: [ "main" ]
  pull_request:
  
jobs:
  fmt:
    name: Rustfmt
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Check code format with Rustfmt
        run: cargo fmt --all -- --check
